[project]
name = "darbiadev-ups"
version = "0.5.0"
description = "darbiadev-ups"
authors = [
    {name = "Bradley Reynolds", email = "bradley.reynolds@darbia.dev"},
]
dependencies = [
    "requests>=2.26.0",
    "python-benedict>=0.24.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[project.urls]
homepage = ""
repository = "https://github.com/darbiadev/darbiadev-ups/"
documentation = "https://darbiadev.github.io/darbiadev-ups/"

[project.optional-dependencies]

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
docs = [
    "sphinx>=4.3.2",
    "sphinxcontrib-autoprogram>=0.1.7",
    "sphinx-rtd-theme>=1.0.0",
    "toml>=0.10.2",
]
test = [
    "pytest>=6.2.5",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.sphinx]
copyright = "Darbia"
author = "Bradley Reynolds"
api_dir = "darbiadev_ups"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39
isolated_build = True
[testenv]
deps =
    pytest
commands =
    pytest
"""
