[project]
name = "darbiadev-ups"
version = "0.6.0"
description = "darbiadev-ups"
readme = "README.md"
authors = [
    { name = "Bradley Reynolds", email = "bradley.reynolds@darbia.dev" },
]
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "requests>=2.26.0",
    "python-benedict>=0.24.3",
]

[project.urls]
repository = "https://github.com/darbiadev/darbiadev-ups/"
documentation = "https://darbia.dev/darbiadev-ups/"

[project.optional-dependencies]

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pip-licenses>=3.5.3",
    "taskipy>=1.9.0",
    "pre-commit>=2.16.0",
    "pylint>=2.12.2",
    "pytest>=6.2.5",
    "pytest-cov>=3.0.0",
    "black>=21.12b0",
]
tests = [
    "pytest>=6.2.5",
]
docs = [
    "sphinx>=4.3.2",
    "sphinxcontrib-autoprogram>=0.1.7",
    "sphinx-rtd-theme>=1.0.0",
    "toml>=0.10.2",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.sphinx]
copyright = "Darbia"
author = "Bradley Reynolds"
api_dir = "darbiadev_ups"

[tool.black]
target-version = ["py310"]
line-length = 120

[tool.pytest.ini_options]
addopts = "tests -r a -v --doctest-modules darbiadev_ups"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = "R1705, R0913, R0914"
# justifications:
# R1705 (no-else-return) - else-return returns error
# R0913 (too-many-arguments) - addresses have lots of fields
# R0914 (too-many-locals) - addresses have lots of fields
