name: Coverage

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PDM
        run: pip install pdm

      - name: Install dependencies
        run: python -m pdm install

      - name: Run tests and generate coverage report
        run: python -m pdm run pytest --cov --disable-warnings -q --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: true
          verbose: true

      - name: Upload Coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
          fail-ci-on-error: true
